# Generated by Django 3.2.8 on 2021-10-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_testimonial_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_key_skill',
            field=models.BooleanField(default=False),
        ),
    ]
